-- Generated by nwg-displays on 2026-10-04 at 15:43:15. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@90.0",
    position = "2560x762",
    scale = 1.6
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@120.0",
    position = "0x0",
    scale = 1.0
})
